# Uncomment the next line to define a global platform for your project
platform :ios,'9.0'


target 'TemplateformSwift' do
    #高斯模糊
#    pod 'DynamicBlurView'
#    #网络判断
#    pod 'ReachabilitySwift'
#    #AFN网络请求Swift版
    pod 'Alamofire'
#    #自动布局MasonrySwift版
#    pod 'SnapKit', '~> 4.0.0'
#    #图片缓存与下载
#    pod 'Kingfisher'
#    #Json——>Model
#    pod 'HandyJSON'
#    #    #Json ->Model
#    #    pod 'SwiftyJSON'
#    #日期
#    pod 'SwiftDate'
#    #图片
#    pod 'SDWebImage'

end


